# -*- coding: utf-8 -*-
"""
架空・総称武将を削除し、実在の史実武将を追加・置換するための準備スクリプト。
"""

# 削除対象の武将ID一覧
fictional_ids_to_remove = [
    'off_sarutobi_sasuke',
    'off_kirigakure_saizo',
    'off_miyoshi_seikai',
    'off_miyoshi_isa',
    'off_anayama_kosuke',
    'off_yuri_kamanosuke',
    'off_kakei_juzo',
    'off_unno_rokuro',
    'off_nezu_jinpachi',
    'off_mochizuki_rokuro',
    'off_dm_otomo_939',
    'off_dm_ezo_native_939',
    'off_dm_shimazu_proto_939',
    'off_dm_ezo_native_1156',
    'off_dm_ezo_native_1180',
    'off_dm_ezo_native_1221',
    'off_dm_ezo_native_1331',
    'off_ezo_kamui_head',
    'off_ezo_ainu_chou1',
    'off_ezo_ainu_chou2',
    'off_ezo_ainu_chou3',
    'off_ezo_ainu_chou4',
    'off_ezo_ainu_chou5',
    'off_ezo_chief_3',
    'off_shimazu_proto_succ3'
]

# 実在の真田家臣・史実武将
real_officers_to_add = [
    {
        "id": "off_yazawa_yoriyasu",
        "name": "矢沢頼康",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 84,
        "politic": 72,
        "intel": 80,
        "era": "sengoku",
        "skill": "沼田の仁王",
        "lore": "真田昌幸の従弟（矢沢頼綱の嫡男）。父とともに沼田城代を務め、北条氏規や後北条氏の大軍による度重なる猛攻を寡兵で撃退し続けた猛将。徳川・上杉・北条の狭間で真田家の生命線である沼田城を死守し、のち松代藩主・真田信之を補佐して家中を支えた。",
        "birthYear": 1553,
        "deathYear": 1626,
        "isDaimyo": False
    },
    {
        "id": "off_takanashi_naiki",
        "name": "高梨内記",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 76,
        "politic": 68,
        "intel": 78,
        "era": "sengoku",
        "skill": "不屈の忠節",
        "lore": "信濃の名族高梨氏の一族で真田昌幸・信繁の重臣。関ヶ原合戦後、信繁に従って九度山へ配流され、十四年余りの困窮生活を共に耐え抜いた。大坂の陣でも大坂城に入城し、真田丸の戦い等で奮戦。夏の陣における信繁の突撃にも従い、最後まで主君に殉じて討死を遂げた。",
        "birthYear": 1560,
        "deathYear": 1615,
        "isDaimyo": False
    },
    {
        "id": "off_oyamada_shigemasa",
        "name": "小山田茂誠",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 75,
        "politic": 82,
        "intel": 76,
        "era": "sengoku",
        "skill": "一門の絆",
        "lore": "信濃小県郡の名族で真田昌幸の長女（村松殿）の夫。武田家滅亡後は北条・徳川の混乱を乗り越えて真田家に仕え、昌幸・信繁・信之を支えた。関ヶ原の戦いでは信之に従い、信之の沼田・上田・松代統治に尽力。松代藩次席家老小山田家の祖となり、家中随一の重臣として重きをなした。",
        "birthYear": 1562,
        "deathYear": 1637,
        "isDaimyo": False
    },
    {
        "id": "off_kawahara_tsunaie",
        "name": "河原綱家",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 70,
        "politic": 80,
        "intel": 75,
        "era": "sengoku",
        "skill": "松代の棟梁",
        "lore": "真田昌幸の義弟（妹婿）で河原隆正の嫡男。犬伏の別れに際しては使者を務め、信之に従って東軍についた。上田合戦やその後の領国再建に奔走し、真田信之の筆頭家老として上田・松代両藩政の基礎を確立。信之が最も信任を寄せた実直堅実な重臣である。",
        "birthYear": 1561,
        "deathYear": 1638,
        "isDaimyo": False
    },
    {
        "id": "off_nezu_masatsuna",
        "name": "祢津昌綱",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 78,
        "politic": 70,
        "intel": 74,
        "era": "sengoku",
        "skill": "滋野の鷹",
        "lore": "信濃の名門滋野三家の一つ・祢津氏（根津氏）の当主。武田信玄・勝頼に仕えたのち、本能寺の変後の天正壬午の乱では真田昌幸と協力して東信濃の独立を維持。のちに真田信之に仕えてその妹を妻とし、真田家の重臣として松代藩祢津氏の祖となった。講談の根津甚八のモデルとされる。",
        "birthYear": 1555,
        "deathYear": 1619,
        "isDaimyo": False
    },
    {
        "id": "off_mochizuki_nobumasa",
        "name": "望月信雅",
        "clanId": "sanada",
        "defaultProv": "north_shinano",
        "military": 74,
        "politic": 76,
        "intel": 72,
        "era": "sengoku",
        "skill": "望月の名族",
        "lore": "滋野三家の一つ信濃望月氏の当主。武田信玄に重用され、望月城主として信濃先方衆を束ねた。武田勝頼の代まで忠節を尽くし、武田氏滅亡後は真田昌幸と血縁を結んで東信濃の国人衆を調停。真田家の信濃・上野平定を支えた名門当主である。講談の望月六郎のルーツとされる。",
        "birthYear": 1535,
        "deathYear": 1605,
        "isDaimyo": False
    },
    {
        "id": "off_miyoshi_masayasu",
        "name": "三好政康",
        "clanId": "toyotomi",
        "defaultProv": "settsu",
        "military": 80,
        "politic": 65,
        "intel": 72,
        "era": "sengoku",
        "skill": "百戦錬磨",
        "lore": "三好三人衆の一人。三好釣閑斎。阿波・山城で三好氏の軍事中核として転戦し、織田信長の上洛後も頑強に抵抗を続けた。晩年は豊臣秀吉に仕え、大坂の陣では八十歳を超える高齢ながら大坂城に馳せ参じて真田信繁らとともに徳川軍に痛撃を与え、討死した。講談の三好清海入道のモデル。",
        "birthYear": 1528,
        "deathYear": 1615,
        "isDaimyo": False
    },
    # 平安・古代の実在武将
    {
        "id": "off_tomo_no_kaneyuki",
        "name": "伴兼行",
        "clanId": "shimazu_proto",
        "defaultProv": "satsuma",
        "military": 78,
        "politic": 75,
        "intel": 72,
        "era": "ancient",
        "skill": "西海の雄略",
        "lore": "平安中期の武将。大伴氏の末裔で薩摩介・大隅弁済使として南九州へ下向。大隅国高山を本拠に在地豪族を従え、大隅・薩摩に武士団を形成して肝付氏の祖となった。承平天慶の乱前後の九州で強い軍事力と統率力を発揮し、南九州武士の先駆となった名将。",
        "birthYear": 905,
        "deathYear": 970,
        "isDaimyo": True
    },
    {
        "id": "off_zaisho_atsuya",
        "name": "税所篤衡",
        "clanId": "shimazu_proto",
        "defaultProv": "osumi",
        "military": 72,
        "politic": 76,
        "intel": 70,
        "era": "ancient",
        "skill": "国衙の牙城",
        "lore": "平安時代の薩摩国在地官人・豪族。薩摩国衙の税所職を代々司り、国府の財政と治安を一手に担った。南九州の在地武士団として勢力を伸ばし、平安後期から鎌倉期にかけて島津氏が入部する以前の薩摩の実質的支配者として家名を後世に伝えた。",
        "birthYear": 910,
        "deathYear": 975,
        "isDaimyo": False
    },
    {
        "id": "off_ando_sadasue",
        "name": "安東貞季",
        "clanId": "ezo_native",
        "defaultProv": "ezo",
        "military": 76,
        "politic": 74,
        "intel": 72,
        "era": "kamakura",
        "skill": "蝦夷管領",
        "lore": "鎌倉時代後期の津軽安東氏（安藤氏）当主。北条得宗家より「蝦夷管領」に任ぜられ、十三湊を拠点に本州と蝦夷島（北海道）を結ぶ北方貿易を一手に掌握した。渡島半島の和人・アイヌ諸集落を統括し、北方世界における一大海上通商圏を築き上げた。",
        "birthYear": 1245,
        "deathYear": 1310,
        "isDaimyo": True
    }
]

print("Defined replacements successfully.")
